config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures
  resources :photos, only: [:new, :create, :index, :destroy]
  root 'pictures#index'
  get '/about' => 'posts#about'
  get '/messages' => 'messages#new'
  post '/messages' => 'messages#create'
  get '/mobile' => 'mobiles#mobile'
  # get '/mobile' => 'messages#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
	include ActiveModel::Model
 	attr_accessor :name, :email, :phone_number, :body
	validates :name, :email, :phone_number, :body, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_attached_file :image, styles: {large: "600x600>", thumbnail: "150x150#"}
	validates_attachment :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	has_attached_file :image, url: "/system/:hash.:extension", hash_secret: "synapp"
end

app/models/picture.rb
class Picture < ApplicationRecord
	has_attached_file :image, styles: {large: "600x600>", thumbnail: "150x150#"}
	 validates_attachment_content_type :image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def new
    @message = Message.new
end

def create

    @message = Message.new(message_params)

    @data = message_params[:body]
    @usr_name = message_params[:name]
    @return_email = message_params[:email]
    @phone_num = message_params[:phone_number]

	if verify_recaptcha(model: @message) && @message.valid?
      ContactMailer.contact_request(@data, @usr_name, @phone_num, @return_email).deliver_now
      redirect_to root_path
      flash[:notice] = "We have received your message and will be in touch soon!"
    else
      flash[:notice] = "There was an error sending your message. Please try again."
      redirect_to messages_path
    end

end

private

def message_params
    params.require(:message).permit(:name, :email, :phone_number, :body)
end

end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!, :except => [:index]
	 def index
    @photos = Photo.order('created_at')
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "The photo was added!"
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def destroy
	@photo = Photo.find(params[:id])
	  @photo.destroy
	  flash[:success] = "The photo was destroyed."
	  redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :content, :image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<%= csrf_meta_tags %>
    <title>Synnple Visuals</title>
    <meta charset="UTF-8">
	<meta name="description" content="Riddle - Portfolio Template">
	<meta name="keywords" content="portfolio, riddle, onepage, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="/assets/favicon_1.ico" rel="shortcut icon"/>
	
	<!-- FontAwesome -->
	<!--
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
-->

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,400i,600,600i,700" rel="stylesheet">

	<!-- Stylesheets -->
	<!--
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/magnific-popup.css"/>
	<link rel="stylesheet" href="css/style.css"/>
	-->
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
	

    <!-- JS -->
    <!--
    <script src="js/jquery-2.1.4.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/mixitup.min.js"></script>
	<script src="js/magnific-popup.min.js"></script>
	<script src="js/main.js"></script>
-->
  </head>

  <body>
	  <% if notice %>
	  	<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
	 	<p class="alert alert-danger"><%= alert %></p>
	  <% end %>
    <%= yield %>
    <div class="footer-sect">
    <p class="navbar-text">
<% if user_signed_in? %>
  Logged in as <strong>Admin</strong>.
 <!-- <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | -->
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <!-- <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | -->
  <%= link_to "Admin Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<% if user_signed_in? %>
	<%= link_to 'Upload', new_photo_path, class: 'btn pull-right navbar-text' %>
<% else %>
<% end %>
</p>
</div>
  </body>
</html>

app/views/layouts/theme.html.erb
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- header section start -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3">
					<div class="logo">
						<h2 class="site-logo">Riddle</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<a href="" class="site-btn header-btn">Get in touch</a>
					<nav class="main-menu">
						<ul>
							<li><a href="home.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="home-2.html">Work</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<div class="nav-switch">
			<i class="fa fa-bars"></i>
		</div>
	</header>
	<!-- header section end -->

	<!-- intro section start -->
	<section class="intro-section">
		<div class="container text-center">
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">I’m a freelance <span>digital designer</span>, with +10 years of experience</h2>
				</div>
			</div>
		</div>
	</section>
	<!-- intro section end -->


	<!-- portfolio section start -->
	<section class="portfolio-section">
		<div class="container">
			<ul class="portfolio-filter controls">
				<li class="control" data-filter="all">All</li>
				<li class="control" data-filter=".web">Web design</li>
				<li class="control" data-filter=".digital">Digital design</li>
				<li class="control" data-filter=".rened">3D Renedering</li>
				<li class="control" data-filter=".brand">Brand Identity</li>
			</ul>
		</div>                       
		<div class="container-fluid p-md-0 ">
			<div class="row portfolios-area">
				<div class="mix col-lg-6 col-md-6 web">
					<a href="img/portfolio/1.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/1.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-6 col-md-6 digital">
					<a href="img/portfolio/2.jpg" class="portfolio-item set-bg " data-setbg="img/portfolio/2.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-4 col-md-6 web">
					<a href="img/portfolio/3.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/3.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-4 col-md-6 digital">
					<a href="img/portfolio/4.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/4.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-4 col-md-6 rened">
					<a href="img/portfolio/5.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/5.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-12 col-md-6 brand">
					<a href="img/portfolio/6.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/6.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-6 col-md-6 rened">
					<a href="img/portfolio/7.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/7.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
				<div class="mix col-lg-6 col-md-6 brand">
					<a href="img/portfolio/8.jpg" class="portfolio-item set-bg" data-setbg="img/portfolio/8.jpg">
						<div class="pi-inner">
							<h2>+ See Project</h2>
						</div>						
					</a>
				</div>
			</div>
		</div>
	</section>
	<!-- portfolio section end -->


	<!-- footer section start -->
	<footer class="footer-section text-center">
		<div class="container">
			<h2 class="section-title mb-5">Let’s work together</h2>
			<a href="" class="site-btn">Get in touch</a>
			<div class="social-links">
				<a href=""><span class="fa fa-pinterest"></span></a>
				<a href=""><span class="fa fa-linkedin"></span></a>
				<a href=""><span class="fa fa-instagram"></span></a>
				<a href=""><span class="fa fa-facebook"></span></a>
				<a href=""><span class="fa fa-twitter"></span></a>
			</div>
			<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</div>
		</div>
	</footer>
	<!-- footer section end -->



	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-2.1.4.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/mixitup.min.js"></script>
	<script src="js/magnific-popup.min.js"></script>
	<script src="js/main.js"></script>
</body>


app/views/messages/new.html.erb
<div id="preloder">
		<div class="loader"></div>
	</div>
	
	<!-- header section start -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3">
					<%= image_tag 'synnple.png', :class => 'logo', :height => '40px', :width => '40px'%>
					<div class="logo">
						<h2 class="site-logo">Synnple Visuals</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<%= link_to 'Get in touch', messages_path, :class => 'site-btn header-btn' %>
					<nav class="main-menu">
						<ul>
							<li><%= link_to 'Home', root_path %></li>
							<li><a href="about.html">About</a></li>
							<li><%= link_to 'Work', photos_path %></li>
							<li><%= link_to'Contact', messages_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<div class="nav-switch">
			<a href="mobile.html"><i class="fa fa-bars"></i></a>
		</div>
	</header>
<section class="intro-section">
		<div class="container text-center">
			<div class="row">

				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">Let us give <span>your business</span> a voice of its own</h2>
				</div>
			</div>
		</div>
	</section>
	<!-- intro section end -->


	<!-- page section start -->
	<section class="page-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 offset-lg-3 contect-tect">
					<h2>So, let’s talk</h2>
					<p>Contact us today using the form below and let us help you push your company to its full potential.</p>
				</div>
			</div>
			<div class='col-lg-6 offset-lg-3 form-field'>
			<%= simple_form_for @message do |f| %>
  			<%= f.input :name, label: 'Your name', placeholder: 'John Smith', error: 'Name is mandatory, please specify one' %>
  			<%= f.input :email, placeholder: 'user@domain.com', error: 'Please enter a valid email' %>
  			<%= f.input :phone_number, placeholder: '(613) 555-5555', error: 'Enter a valid phone number' %>
  			<%= f.input :body, :as => :text, label: 'Message', :input_html => { 'rows' => 5, :style => 'width: 600px'},  placeholder: 'How can we help you?', error: 'Enter your message' %>
  			<%= recaptcha_tags %>
  			<div>
  			<%= f.button :submit %>
  			</div>
			<% end %>
		</div>
		</div>
	</section>
	<!-- page section end -->

	<!-- footer section start -->
	<footer class="footer-section text-center">
		<div class="container">
			<div class="social-links">
				<a href="https://youtube.com/synnple"><span class="fa fa-youtube"></span></a>
				<a href="https://instagram.com/synnple"><span class="fa fa-instagram"></span></a>
				<a href="https://facebook.com/synnple"><span class="fa fa-facebook"></span></a>
				<a href="https://twitter.com/synnple"><span class="fa fa-twitter"></span></a>
			</div>
			<div class="copyright">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website is made by <a href="https://instagram.com/galenhammond17" target="_blank">Galen Hammond</a>

</div>
		</div>
	</footer>


app/views/messages/show.html.erb
!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- header section start -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3">
					<%= image_tag 'synnple.png', :class => 'logo', :height => '40px', :width => '40px'%>
					<div class="logo">
						<h2 class="site-logo">Synnple Visuals</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<a href="" class="site-btn header-btn">Get in touch</a>
					<nav class="main-menu">
						<ul>
							<li><a href="home.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><%= link_to 'Work', new_picture_path %></li>
							<li><%= link_to 'Contact', messages_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<div class="nav-switch">
			<a href="mobile.html"><i class="fa fa-bars"></i></a>
		</div>
	</header>
	<!-- header section end -->

	<!-- intro section start -->
	<section class="intro-section">
	<!--
		<div class="jumbotron">
			<%= image_tag 'synnple.png', :height => '105x', :width => '105x' %>
		</div>
	-->	

app/views/mobiles/mobile.html.erb
<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3 logo">
					<%= image_tag 'synnple.png', :class => 'logo', :height => '40px', :width => '40px'%>
					<div class="logo">
						<h2 class="site-logo">Synnple Visuals</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<%= link_to 'Get in touch', messages_path, :class => 'site-btn header-btn' %>
					<nav>
						<ul>
							<li><%= link_to 'Home', root_path %></li>
							<li><a href="about.html">About</a></li>
							<li><%= link_to 'Work', photos_path %></li>
							<li><%= link_to 'Contact', messages_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>

app/views/photos/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/photos/_form.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo do |f| %>
  <%= render 'errors', object: @photo %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/photos/_photo.html.erb

<div class="media">
  <div class="media-left">

   <%= link_to image_tag(photo.image.url, class: 'media-object') %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= photo.title %></h4>
    <% if user_signed_in? %>
    	<%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
	<% else %>
	     <div>	
    	</div>
	<% end %>
  </div>
</div>

app/views/photos/index.html.erb
<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- header section start -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3 logo">
					<%= image_tag 'synnple.png', :class => 'logo', :height => '40px', :width => '40px'%>
					<div class="logo">
						<h2 class="site-logo">Synnple Visuals</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<%= link_to 'Get in touch', messages_path, :class => 'site-btn header-btn' %>
					<nav class="main-menu">
						<ul>
							<li><%= link_to 'Home', root_path %></li>
							<li><a href="about.html">About</a></li>
							<li><%= link_to 'Work', photos_path %></li>
							<li><%= link_to 'Contact', messages_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<div class="nav-switch">
			<a href="mobile.html"><i class="fa fa-bars"></i></a>
		</div>
	</header>
<section class="intro-section">
		<div class="container text-center">
			<div class="row">

				<div class="col-xl-10 offset-xl-1">
					<h2 class="section-title">Check out <span>our portfolio</span> of some of our most recent work</h2>
				</div>
			</div>
		</div>
	</section>
	<!-- intro section end -->


	<!-- page section start -->
	<section class="page-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 offset-lg-3 contect-tect">
<%= render @photos %>
<footer class="footer-section text-center">
		<div class="container">
			<h2 class="section-title mb-5">Let’s work together</h2>
			<%= link_to 'Get in touch', messages_path, :class => 'site-btn' %>
			<div class="social-links">
				<a href="https://youtube.com/synnple"><span class="fa fa-youtube"></span></a>
				<a href="https://instagram.com/synnple"><span class="fa fa-instagram"></span></a>
				<a href="https://facebook.com/synnple"><span class="fa fa-facebook"></span></a>
				<a href="https://twitter.com/synnple"><span class="fa fa-twitter"></span></a>
			</div>
			<div class="copyright">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This website is made by <a href="https://instagram.com/galenhammond17" target="_blank">Galen Hammond</a>

</div>
		</div>
	</footer>

app/views/photos/new.html.erb
<h1>New Picture</h1>


<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/pictures/_form.html.erb
<%= form_for @picture, html: {multipart: true} do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>
<!-- <div class="field">
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index1.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', root_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- header section start -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-3 logo">
					<%= image_tag 'synnple', :class => 'logo', :height => '40px', :width => '40px'%>
					<div class="logo">
						<h2 class="site-logo">Synnple Visuals</h2>
					</div>
				</div>
				<div class="col-lg-8 col-md-9">
					<a href="" class="site-btn header-btn">Get in touch</a>
					<nav class="main-menu">
						<ul>
							<li><%= link_to 'Home', root_path %></li>
							<li><a href="about.html">About</a></li>
							<li><%= link_to 'Work' %></li>
							<li><%= link_to 'Contact', messages_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
		<div class="nav-switch">
			<a href="mobile.html"><i class="fa fa-bars"></i></a>
		</div>
	</header>